# Uncomment this line to define a global platform for your project
platform :ios, '15.5'

# CocoaPods analytics sends usage stats. Change to false to disable.
COCOAPODS_DISABLE_ANALYTICS = true

flutter_install_all_ios_pods File.expand_path(File.join('..', '.flutter-plugins-dependencies'), __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..', '.flutter-plugins-dependencies'), __FILE__)

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Force deployment target to 15.5 for all pods
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
